server:
  port: 9009


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yanghan
    druid:
      #配置初始化大小、最大、最小
      initial-size: 5
      max-active: 20
      min-idle: 10
      #获取连接等待时间
      max-wait: 30000
      #连接在池中的生存时间
      min-evictable-idle-time-millis: 30000
      #检测间隔时间，关闭空闲连接
      time-between-eviction-runs-millis: 2000
      keep-alive: true
      filters: stat
      # 开启监控页面
      stat-view-servlet:
        enabled: false
        # IP白名单
        allow: 127.0.0.1
