server:
  port: 9001

spring:
  profiles:
    active: dev
  application:
    #bootstrap先加载，读不到pom，在application中有效
    name: @pom.artifactId@

logging:
  level:
    org.springframework.security: DEBUG
