spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_base?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: yanghan
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: yh-file
  servlet:
    # 文件上传大小限制
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yh.cloud.sys.model.entity


server:
  port: 9031


swagger:
  enabled: true
  version: 2.0
  base-path: /**
  exclude-path: /error
  authorization:
    key-name: Authorization
  base-package: com.yh.cloud

# 文件上传器
yh:
  uploader:
    enabled: true
    default-type: database
    ordinary:
      path: /usr/yh_upload
      domain: http://127.0.0.1:8038
    minio:
      enabled: true
      endpoint: http://120.24.61.XX:8301
      access-key:
      secret-key:
      bucket-name: testdemo
    aliyun:
      enabled: false
      endpoint: http://xxx
      access-key:
      secret-key:
      bucket-name: testdemo
  audit-log:
    enabled: true


# 日志
logging:
  level:
    com.yh: debug
  file:
    # 在指定目录下生成spring.log文件
    path: /usr/yh_log
